src/main/java/com/example/demo/TodacApplication.java
=> feat : #테스트 김나혜 240130

src/main/java/com/example/demo/TodacApplication.java
=> feat : #git test 유서연 [240130]

src/main/reactjs/src/Footer.js
- PascalCase로 작명 수정하여 warning 제거
=> style: #아이콘 장원태 [240202] - icon 태그의 작명 수정

src/main/reactjs/src/routers/RouterUserMain.js, src/main/reactjs/src/routers/user/chat/RouterChat.js, src/main/reactjs/src/routers/user/community/RouterBoard.js, src/main/reactjs/src/routers/user/community/RouterCommunityHome.js, src/main/reactjs/src/routers/user/community/RouterDonation.js, src/main/reactjs/src/routers/user/community/RouterFace.js, src/main/reactjs/src/routers/user/mypage/RouterFAQ.js, src/main/reactjs/src/routers/user/mypage/RouterInquiry.js, src/main/reactjs/src/routers/user/mypage/RouterMypage.js
conflict 최소화를 위해 RouterUserMain의 구조를 세분화하였습니다.
=> refactor: #라우터 장원태 [240205] - RouterUserMain.js 세분화

src/main/java/mypage/controller/PaymentController.java
=> fix : #마이페이지 김동현 [240205] - 결제 컨트롤러 주석 처리

src/main/java/login/service/LoginServiceImpl.java, src/main/reactjs/src/components/admin/AdminMain.js, src/main/reactjs/src/components/login/LoginAdmin.js, src/main/reactjs/src/components/login/LoginCallBack.js, src/main/reactjs/src/components/login/LoginMain.js, src/main/reactjs/src/components/mypage/MypageMain.js
- 로그인시 세션스토리지에 토큰,id 저장하기
- 로그아웃시 세션스토리지 지우기
해줘!!!!!!!!!!!!
=> feat : #로그인 김나혜 [240205] 세션스토리지-토큰,id

src/main/reactjs/src/components/chat/chattingroom/ChatRoomHeader.js, src/main/reactjs/src/components/chat/chattingroom/ChatRoomMain.js, src/main/reactjs/src/components/chat/chattingroom/ChatRoomStyle.css
- input의 초기 상태값을 빈 문자열로 수정
- 채팅창의 높이가 반응형으로 맞춰지도록 변경
사소한 변경이지만 한번씩만 부탁드려요!!
=> fix: #인공지능채팅 장원태 [240205]

src/main/reactjs/src/components/chat/document/ChatSummary.js, src/main/reactjs/src/components/chat/document/DocumentStyle.css
브렌치가 진단서 브렌치인데 진단서 하다가 요약본 디자인 수정해서 그렇습니다~~
=> design: #ChatSummary 이재영 [240205] - 채팅 요약본 부분 디자인

src/main/java/mypage/controller/MemberController.java, src/main/java/mypage/repository/MemberDao.java, src/main/reactjs/src/components/admin/AdminMain.js, src/main/reactjs/src/components/admin/AdminStyle.css, src/main/reactjs/src/components/admin/user/MemberManage.js
=> feat: #관리자 페이지 유서연 [240206]  - 회원 관리

src/main/reactjs/src/components/chat/document/ChatSummary.js, src/main/reactjs/src/components/chat/document/DocumentStyle.css
이번에도 실수롤 진단서 브렌치에서 요약본 디자인을 했네여..^^
=> design: #ChatSummary 이재영 [240206] - 채팅 요약본 디자인

src/main/reactjs/src/components/chat/document/ChatDiagnosis.js, src/main/reactjs/src/components/chat/document/ChatSummary.js, src/main/reactjs/src/components/chat/document/DocumentStyle.css
- 진단서 페이지 구성
- 진단서 페이지 기초 베이스 디자인
=> feat: #ChatDiagnosis 이재영 [240206] - 채팅 진단서

src/main/reactjs/public/index.html, src/main/reactjs/src/components/chat/chattingroom/ChatReviewModal.js
- 기타: ChatReviewModal 컴포넌트에서 쓰이지 않는 함수 제거
=> fix: #기타 장원태 [240206] - 헤더에 꺾새가 표시되던 현상 수정

src/main/java/chat/controller/ChatController.java, src/main/java/chat/repository/ChatDao.java, src/main/java/chat/service/ChatService.java, src/main/reactjs/src/components/chat/api/gpt.js, src/main/reactjs/src/components/chat/chattingroom/ChatRoomMain.js, src/main/reactjs/src/routers/RouterAdminMain.js, src/main/reactjs/src/routers/RouterUserMain.js
채팅창
1. 채팅방 및 채팅로그 데이터 DB에 저장 구현
2. 별점을 스킵하는 경우에 한해 로그 저장 후 요약본 페이지로 이동
전체 디자인
1. 오늘 추가했던 로그인 관련 및 채팅 관련 sweetalert의 버튼의 색과 텍스트를 다른 alert창과 동일하게 수정
=> 채팅방 & 전체 sweetalert 디자인 수정입니다

src/main/java/login/repository/LoginDao.java, src/main/java/login/service/LoginService.java, src/main/java/login/service/LoginServiceImpl.java, src/main/reactjs/src/components/mypage/MypageMain.js
=> fix : #로그인 김나혜 [240207]

src/main/java/login/service/LoginServiceImpl.java, src/main/reactjs/src/components/login/LoginCallBack.js, src/main/reactjs/src/components/mypage/MypageMain.js
- 마이페이지에 usercode 보내기 (수정)
- 잘못짜서 마이페이지 송출이 안되서 방금 고쳤어요 다시 풀리퀘 해주세욤
=> fix : #login [김나혜] 240207 - 마이페이지에 usercode 보내기 (수정)

src/main/reactjs/src/components/CommonStyle.css, src/main/reactjs/src/components/PageHeader.js, src/main/reactjs/src/components/chat/chattingroom/ChatRoomMain.js
각자 페이지에 들어갈 공통 헤더를 구현했습니다.
확인해주시고, 각자 사용해보시다가 문제 생기면 말씀 주세요!
사용 방법은 Slack에 적어놓겠습니다.
=> feat: #페이지헤더 장원태 [240207] - 공통 페이지 헤더 구현

src/main/reactjs/src/components/chat/api/gpt.js, src/main/reactjs/src/components/chat/chattingroom/ChatContent.js, src/main/reactjs/src/components/chat/chattingroom/ChatLoading.css, src/main/reactjs/src/components/chat/chattingroom/ChatRoomMain.js
1. 사용자 입력 전송 시 입력 즉시 제거 & 채팅창에 띄우기
2. 채팅 로딩 기능 구현
3. 채팅이 갱신되면, 자동스크롤되도록 개선
=> 채팅 개선 작업 진행하였습니다

src/main/java/chat/data/CounselorDto.java
테이블 구조에 변경이 가는만큼 바로 pr 보내드립니다. 최신화 부탁드려요!
=> CounselorDto에 새로운 컬럼인 greeting 추가

src/main/java/mypage/controller/PointRecordController.java, src/main/java/mypage/repository/PointRecordDao.java, src/main/java/mypage/repository/PointRecordRepository.java, src/main/reactjs/src/components/admin/user/MemberPayment.js, src/main/reactjs/src/components/admin/user/MemberProfile.js
feat : #관리자 페이지 유서연 [240214]
-회원 결제내역 페이지 전체 기능 구현 완료
=> feat : #관리자 페이지 유서연 [240214]

src/main/reactjs/src/components/admin/user/MemberPoint.js
feat : #관리자 게시판 유서연 [240214]
- 회원 포인트 사용 내역 페이지 기능 구현 완료
(근데 제가 결제페이지, 포인트 페이지 각 컬럼명이 헷갈려서 설명을 듣고 일부 수정해야할거 같습니다)
=> feat : #관리자 게시판 유서연 [240214]

src/main/reactjs/src/components/admin/user/MemberComments.js, src/main/reactjs/src/components/admin/user/MemberManage.js, src/main/reactjs/src/components/admin/user/MemberPayment.js, src/main/reactjs/src/components/admin/user/MemberPoint.js, src/main/reactjs/src/components/admin/user/MemberPost.js
- 회원 게시글, 회원 댓글, 회원, 회원 포인트 사용내역 페이징처리 완료
=> feat : #관리자페이지 유서연 [240215]

src/main/reactjs/src/components/chat/ChatMain.js, src/main/reactjs/src/components/chat/counselor/CounselorStyle.css, src/main/reactjs/src/components/chat/counselor/LogNavigationButton.js
1. 상담사 선택창 첫 로드 시 '토닥봇'이 기본으로 선택되도록 개선
2. 상담사 선택창에서 '나의 상담기록' 버튼 추가(채팅로그 쪽은 아직 미구현)
=> 오늘 회의에서 나온 피드백 사항 일부 적용했습니다

src/main/reactjs/src/components/login/Login.css, src/main/reactjs/src/components/login/SignupKaKao.js, src/main/reactjs/src/components/login/SignupNaver.js
-로그인 메인화면, 로그인콜백 하단 공백생기던거 수정
-카카오 로그인, 네이버로그인 css수정
=> design #로그인css 한충희 [240216]

src/main/reactjs/src/components/CommonStyle.css, src/main/reactjs/src/routers/RouterStartMain.js
=> design #스타트메인페이지 로고 한충희 [240218]

src/main/reactjs/src/components/chat/chattinglog/ChattingLogList.js, src/main/reactjs/src/components/chat/chattinglog/ChattingLogStyle.css, src/main/reactjs/src/components/chat/chattinglog/list/ChatListFilter.js, src/main/reactjs/src/components/chat/chattingroom/ChatRoomMidBar.js, src/main/reactjs/src/components/chat/chattingroom/ChatRoomStyle.css
1. 나의 상담 기록 리스트 - 날짜 기준 오름/내림차순 정렬(선택 상담사 유지)
2. 나의 상담 기록 리스트 - 상담사별 리스트 출력(날짜 순서 유지)
3. 채팅 - 종료 버튼 스타일 수정
=> 상담 기록 리스트 정렬/상담사 필터링 구현 및 일부 스타일 수정입니다

src/main/java/login/service/LoginServiceImpl.java, src/main/reactjs/src/components/mypage/MypageMain.js
=> fix : # 마이페이지 유서연 [20240221]

src/main/reactjs/src/components/CommonStyle.css, src/main/reactjs/src/components/chat/counselor/CounselorStyle.css, src/main/reactjs/src/components/mypage/MyPageStyle.css, src/main/reactjs/src/routers/RouterStartMain.js
- footer에 대한 align-self를 flex-end로 지정
- height: 100%였던 일부 페이지 main div에 대해 해당 스타일 해제
=> fix: #footer 장원태 [240222] - footer가 일부 환경에서 페이지의 하단부를 가리는 현상 수정

src/main/reactjs/package-lock.json, src/main/reactjs/package.json, src/main/reactjs/src/components/chat/ChatMain.js, src/main/reactjs/src/components/chat/counselor/CounselorCardBack.js, src/main/reactjs/src/components/chat/counselor/CounselorCardFront.js, src/main/reactjs/src/components/chat/counselor/CounselorCardLast.js, src/main/reactjs/src/components/chat/counselor/CounselorOptions.js, src/main/reactjs/src/components/chat/counselor/CounselorProfile.js, src/main/reactjs/src/components/chat/counselor/CounselorStyle.css
1. 상담사 선택 - 카드 UI 도입
2. '나만의 상담사 제작' 기능 도입할 수도 있어, 임시로 카드 하나 제작
=> 상담사 목록 UI 개선중 - 일단 pr 보냅니다

src/main/reactjs/src/components/admin/AdminMain.js, src/main/reactjs/src/components/login/LoginCallBack.js, src/main/reactjs/src/components/login/LoginMain.js, src/main/reactjs/src/routers/RouterAdminMain.js, src/main/reactjs/src/routers/RouterStartMain.js, src/main/reactjs/src/routers/RouterUserMain.js
- 첫 로드 시 로그인 여부와 무관하게 스타트페이지가 나오도록 수정
- 스타트페이지의 레이아웃에 헤더와 푸터가 나오지 않도록 수정
- 다른 페이지 이동할 때 로그인이 되어 있지 않은 경우, Swal창 없이 바로 이동하도록 개선
- 관리자페이지의 로그아웃 아이콘 클릭 시 로그아웃이 되지 않는 현상 수정
- 로그인 페이지에서 class 속성 사용으로 인해 warning이 뜨던 현상 수정
[commit message에 잊은 부분]
- 로그인 성공 시, 채팅 목록으로 바로 이동하도록 수정
=> feat: #라우터 장원태 [240223] - 스타트페이지 관련 라우터 수정 및 일부 오류 수정

src/main/reactjs/src/components/admin/user/MemberPost.js, src/main/reactjs/src/components/admin/user/MemberPostDetail.js
=> fix : # 관리자 게시판 유서연  [20240223] 회원 게시글 검색 페이지

src/main/java/chat/data/CounselorDetailInterface.java, src/main/java/chat/repository/CounselorRepository.java, src/main/reactjs/src/components/chat/counselor/CounselorOptions.js
=> 상담사 개선: 카드 색깔을 DB로부터 불러오도록 개선

src/main/reactjs/src/components/admin/user/MemberChatHistory.js, src/main/reactjs/src/components/admin/user/MemberChatSearch.js, src/main/reactjs/src/components/admin/user/MemberPayment.js, src/main/reactjs/src/components/admin/user/MemberPoint.js
해당 회원의 채팅 로그 띄우기
fix : # 관리자 게시판 유서연  [20240223]
payment - 줄간격 수정
point- 포인트 출력 단위를 P로 수정
=> feat : # 관리자 게시판 유서연  [20240223] 회원 상세 채팅 페이지

src/main/java/chat/controller/ChatController.java, src/main/java/chat/repository/ChatRoomRepository.java, src/main/reactjs/src/components/chat/chattinglog/ChattingLogContent.js, src/main/reactjs/src/components/chat/chattinglog/content/ChatLogButtons.js, src/main/reactjs/src/components/chat/counselor/CounselorStyle.css
1. 나만의 상담사 만들기 카드 - 백그라운드에 아기토닥봇 추가
2. 타입 수정: findByChatroom 메소드의 타입이 수정됨에 따라 ChatController에 발생했던 타입 오류 수정
3. 오류 수정: counselor 테이블에 새 foreign key가 등장함에 따라, '나의 상담 로그'에서 상담사의 이름을 불러오지 못하던 현상 수정
4. 나의 상담 로그 - 뒤로가기 버튼을 요약본 확인 버튼으로 대체
=> 상담사 - 일부 개선

src/main/reactjs/src/components/CommonStyle.css, src/main/reactjs/src/components/chat/counselor/LogNavigationButton.js
- 공용 하얀색 버튼 추가
- 버튼 길이 관련 css 분리
- 상담기록 버튼에 하얀 버튼 적용
=> feat: #버튼추가 장원태 [240228]

src/main/reactjs/src/components/chat/document/ChatDiagnosis.js, src/main/reactjs/src/components/chat/document/ChatSummary.js
- 요약본 페이지와 진단서 페이지 하단의 버튼을 공통 버튼으로 변경
- 각 칸의 색상 변경해야 함
=> feat: #요약본 페이지, 진단서 페이지 이재영 [240228] - 공통 버튼으로 변경

src/main/reactjs/src/components/community/game/GameMain.js, src/main/reactjs/src/components/login/LoginCallBack.js, src/main/reactjs/src/components/login/LoginMain.js, src/main/reactjs/src/components/login/SignupKaKao.js, src/main/reactjs/src/components/login/SignupNaver.js
- 회원 가입 css 수정
- 게임 뱃지 알람 창 수정
=> fix : css 수정 김나혜 240229 

src/main/reactjs/src/components/CommonStyle.css, src/main/reactjs/src/components/chat/chattingroom/ChatRoomMain.js, src/main/reactjs/src/components/chat/counselor/CounselorStyle.css, src/main/reactjs/src/components/chat/counselorcustom/create/CounselorCreateTable.js, src/main/reactjs/src/utils/achieveAlert.js
1. 나만의 상담사 만들기 폼에서 몇개만 input_text 클래스 적용 시도. 이들 모두 MUI를 사용하는 것으로, 추가적인 작업 필요할 듯.
2. 테스트용 업적 Swal 삭제
3. input_text 클래스에 outline: deepblue 추가
4. Safari 환경 일부에서 뒷면의 버튼이 앞면에서도 보이는 현상 추가 수정 시도
=> 테스트 중인데, 배포를 위해 한번 합치겠습니다

src/main/reactjs/src/components/admin/user/MemberPoint.js
- 포인트 사용 내역 TP로 단위 통일
- 채팅 기록, 포인트 사용에서 회원 정보로 갈 때 400 에러 오류 해결
=> fix: #관리자페이지 유서연 [240229] - 최종 변경사항 수정

src/main/reactjs/src/components/admin/AdminStyle.css, src/main/reactjs/src/components/admin/user/MemberChatHistory.js, src/main/reactjs/src/components/admin/user/MemberChatSearch.js, src/main/reactjs/src/components/admin/user/MemberManage.js, src/main/reactjs/src/components/admin/user/MemberProfile.js, src/main/reactjs/src/components/admin/user/ViewListFilter.js
-버튼 오른쪽 마진 없애기
- 테이블의 전체 항목들 가운데 정렬로 수정
=> fix: #관리자 페이지 유서연  [240301] -  회원 관리 페이지

src/main/reactjs/src/components/chat/document/ChatDiagnosis.js, src/main/reactjs/src/components/chat/document/ChatSummary.js
- swal창 스타일 변경
- 사용하지 않는 코드 제거
=> fix: #ChatSummary, ChatDiagnosis 이재영 [240301]

src/main/reactjs/src/components/admin/user/MemberPoint.js
=> feat: #관리자페이지 유서연 [240302] - 회원포인트내역

src/main/reactjs/src/components/admin/user/MemberChatSearch.js
진단서발급여부 필터링해주는 기능 추가 구현 (css는 추후 구현 아마 1시간내로...ㅎㅎ)
=> feat: #관리자페이지 유서연 [240302] - 회원채팅내역

src/main/reactjs/src/components/community/donation/DonationMain.js, src/main/reactjs/src/components/community/donation/DonationMainContent.js, src/main/reactjs/src/components/community/donation/DonationMainStyle.css
=> design #후원의전당 한충희 [240302]

src/main/java/chat/controller/ChatDiagnosisController.java, src/main/java/chat/repository/ChatDiagnosisRepository.java, src/main/java/chat/service/ChatDiagnosisService.java, src/main/reactjs/src/components/chat/document/ChatDiagnosis.js
- 진단서 1회 발급 시 얻는 업적 코딩
- 아직 업적이 만들어지지 않아서 확인은 못해봄 -> 업적이 만들어지면 바로 확인 예정
=> feat: #ChatDiagnosis 이재영 [2403030] - 진단서 부분 업적 생성

src/main/reactjs/src/components/admin/user/MemberManage.js
- 검색시 검색결과에 대한 페이징처리가 되지 않고 계속 전체 페이지에 대한 페이징처리가 되는 문제 해결
=> fix: #관리자 페이지 유서연 [240303] - 회원관리

src/main/reactjs/src/components/community/CommunityMain.js, src/main/reactjs/src/components/community/game/GameMain.js, src/main/reactjs/src/components/login/LoginCallBack.js, src/main/reactjs/src/components/login/SignupKaKao.js, src/main/reactjs/src/components/login/SignupNaver.js, src/main/reactjs/src/components/mypage/point/Pointcheck.js, src/main/reactjs/src/utils/badgeInfo.js
- '오늘의미소 -> 미소팡팡' 이름변경
- 로그인 처리 오류시 뒤로가기 nav 설정
- 회원가입 swal창 css변경
=> fix : css 수정 김나혜 240304

src/main/reactjs/src/components/admin/user/MemberChatSearch.js
=> fix: #관리자 페이지 유서연 [240304]

README.md
- 나머지 조원들의 프로젝트 후기 기입
- 조원의 역할에 DB설계 역할 추가 및 일부 역할 정리
- 발표 영상에, 시작 시간이 기입된 풀 라이브 영상으로 링크 등록
- 토글 태그의 크기가 github 상에서 정상적으로 커지지 않는 현상 수정
=> docs: #리드미 장원태 [240311] - 3월 11일자 내용 추가 및 보완
